### ISSUE TITLE
"/dev/bus/usb": not a device node

### ISSUE THREAD

**Issue by electrojit** [mwinters-stuff/vscode-devcontainer-raspberrypi-pico#2]
Good day and thank you for this repo.

When I try to open the Remote Container - after building it threw the error:

"Error response from daemon: error gathering device information while adding custom device "/dev/bus/usb": not a device node."

I tried to google but not sure what is the exact root cause for this error.

Is it possible to help or share your host  details?

I am trying it on Ubuntu 22.04.1 LTS, AMD based CPU.

Thank you.

**Comment by mwinters-stuff** [comment]
I would guess, that you do not have the required privileges.. check that your user you are using can see /dev/bus/usb/** and that your docker process is running as root..
eg.
```
ps -aef | grep docker
root        4617       1  0  2022 ?        00:04:29 /usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375
```

**Comment by electrojit** [comment]
Thank you very much for the kind reply. It turns out that docker desktop somehow does not support it. I had uninstalled it and then installed docker cli manually and after that it is working fine.

Thank you once again.
