### ISSUE TITLE
Need root privileges to run OpenOCD

### ISSUE THREAD

**Issue by johnheaven** [mwinters-stuff/vscode-devcontainer-raspberrypi-pico#3]
Hi,

First of all, thanks for sharing this great project!

I got debugging working a couple of weeks ago but today I've been having problems. The error I get is that no CMSIS-DAP device can be found. I tried running the OpenOCD command to copy across a compiled binary and it only worked if I used `sudo`.

I changed `.devcontainers/devcontainer.json` to run as `root` (`"remoteUser": "root"` at the bottom) and now it works again. Is this the "right" way to do it or there a better way?

**Comment by mwinters-stuff** [comment]
You might not have enough permissions for /dev/bus/usb which you will see is mounted into the container, your user might need to be added to the group that /dev/bus/usb is a member of.

**Comment by mwinters-stuff** [comment]
Ok, got on my PC.. Have a look at the readme.md, you need to install the udev rules.. (I suspect you have not).
