### ISSUE TITLE
Minor Documentation Edits Required

### ISSUE THREAD

**Issue by xjordanx** [mwinters-stuff/vscode-devcontainer-raspberrypi-pico#5]
First of all THANK YOU this is a VERY helpful thing you have done!

That said, your instructions say to:
"Copy the contents of .devcontainer into your project
Copy the contents of .vscode into your project"

But this is not in fact what is required. What is required is actually to copy the entire folders:
(check-out folder) vscode-devcontainer-raspberrypi-pico\
.devcontainer
.vscode
... and their contents, into the target project folder in which you wish to develop a Pi PICO project.

This will make your solution even more accessible especially to students and hobbyists who are not yet familiar with Dev Containers.

**Comment by mwinters-stuff** [comment]
Made some changes. Thanks.
